blog/urls.py
#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views
from users import views as u_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/login/$', views.login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^users/logout/$', views.logout, {'next_page': '/blog/'}, name='logout'),
    url(r'^users/register/$', u_views.register, name='register'),

    url(r'^blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.utils import timezone


class Post(models.Model):
    author         = models.ForeignKey('auth.User')
    title          = models.CharField(max_length=200)
    text           = models.TextField()
    created_date   = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blog/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
from .forms import PostForm

# Create your views here.

def post_list(request):
    posts = Post.objects.all().order_by('-created_date')
    return render(request, 'blog/post_list.html', locals())

@login_required
def post_detail(request, pk):   # primary key
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', locals())

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:                       # GET
        form = PostForm()
    return render(request, 'blog/post_edit.html', locals())

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('post_detail', pk=post.pk)
    form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', locals())

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('post_list')
    else:                       # GET
        form = UserCreationForm()
    return render(request, 'users/register.html', locals())

blog/templates/blog/base.html
{% load bootstrap3 %}
{% load wysiwyg %}
<!DOCTYPE html>
<html lang="en">
    <head>
	<meta charset="utf-8">
	<title>Blog</title>
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	{% wysiwyg_setup %}
    </head>
    <body>
	<div class="container">
	    <div class="jumbotron" style="padding: 1em">
		{% if user.is_authenticated %}
		    <div class="row">
			<div class="col-md-8"></div>
			<div class="col-md-4">
			    <ol class="breadcrumb">
				<li><a href="#">{{ user.username }}</a></li>
				<li><a href="{% url 'post_list' %}">Home</a></li>
				<li><a href="{% url 'logout' %}" style="color: grey">logout</a></li>
			    </ol>
			</div>
		    </div>
		{% endif %}
		<h2>Write Your Blogs</h2>
		<p>A repository to record your daily life</p>
		{% if not user.is_authenticated %}
		    <p>
			<a class="btn btn-primary btn-default" href="{% url 'login' %}" role="button">Login</a>
			<a class="btn btn-primary btn-default" href="{% url 'register' %}" role="button">Register</a>
		    </p>
		{% else %}
		    <a class="btn btn-primary btn-sm" href="{% url 'post_new' %}" role="button">Post New</a>
		{% endif %}
	    </div>
	    {% block content %}
            {% endblock %}
	</div>
    </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div>
	<h1>{{ post.title }}</h1>
	<p>created: {{ post.created_date }} by {{ post.author.username }}</p>
	<p>{{ post.text | safe | linebreaksbr }}</p>
    </div>
    {% if post.author == user %}
	<a class="btn btn-xs btn-success" href="{% url 'post_edit' pk=post.pk %}">edit</a>
	<a class="btn btn-xs btn-danger" href="{% url 'post_remove' pk=post.pk %}">delete</a>
    {% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load wysiwyg %}

{% block content %}

{% if form.errors %}
    <p>content is invalid, please modify</p>
{% endif %}

<form method="POST">
    {% csrf_token %}

    <div class="form-group">
	<label for="id_title">{{ form.title.label_tag }}</label>
	<input type="text" maxlength="100" class="form-control" name="title" id="id_title" value="{{ form.title.value }}" required>
	<br/>
	<label for="id_text">{{ form.text.label_tag }}</label>
	<textarea class="form-control" id="id_text" rows="30" name="text" required>{{ form.text.value }}</textarea>
	{% wysiwyg_editor "id_text" %}
    </div>

    {#{ form.as_p }#}
    <button type="submit">submit</button>
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
	<div class="page-header">
	    <h3>
		<a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
	    </h3>
	    <small>created: {{ post.created_date }} by {{ post.author.username }}</small>
	    <!-- <p>{{ post.text | linebreaksbr }}</p> -->
	</div>
    {% endfor %}
{% endblock %}

users/templates/users/login.html
{% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

users/templates/users/register.html
<form method="post" action="{% url 'register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="register" />
</form>